# Generated by Django 2.2.24 on 2023-06-01 12:16

from django.db import migrations


def fill_field_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.ojects.all():
        if flat.construction_year<2015:
            flat.new_building=False
        else:
            flat.new_building=True




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_field_new_building),
    ]



