# Generated by Django 2.2.24 on 2023-06-02 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_flats', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
