# Generated by Django 3.2 on 2023-06-02 07:14

from django.db import migrations
import phonenumbers
from django.db.models import Case, Value, When, F

def valid_number(number):
    try:
        phonenumber = phonenumbers.parse(number, 'RU')
    except phonenumbers.phonenumberutil.NumberParseException:
            return None
    return phonenumbers.is_valid_number(phonenumber)

def copy_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        if valid_number(flat.phonenumber):
            flat.pure_phone = phonenumbers.format_number(phonenumbers.parse(flat.phonenumber,
                                                               'RU'), phonenumbers.PhoneNumberFormat.E164)
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(copy_number),
    ]
