# Generated by Django 3.2 on 2023-06-02 18:20

from django.db import migrations


def make_copy_of_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner,
            owner_pure_phone=flat.owner_pure_phone,
            owners_phonenumber=flat.owners_phonenumber,)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20230602_2036'),
    ]

    operations = [
    migrations.RunPython(make_copy_of_owner),
    ]
